"""Expose the PhantomX walking task and registration helpers."""

from .config import (
    PHANTOMX_COMMAND_FIELDS,
    PHANTOMX_DISCRETE_TERRAIN_ENVIRONMENT_ID,
    PHANTOMX_DISCRETE_TERRAIN_TASK_ID,
    PHANTOMX_ENVIRONMENT_ID,
    PHANTOMX_FEET,
    PHANTOMX_PURSUIT_ENVIRONMENT_ID,
    PHANTOMX_PURSUIT_TASK_ID,
    PHANTOMX_ROBOT_ID,
    PHANTOMX_SLOT_ISOLATED_ENVIRONMENT_ID,
    PHANTOMX_TASK_ID,
    PHANTOMX_TASK_VERSION,
    PHANTOMX_TERRAIN_ENVIRONMENT_ID,
    PHANTOMX_TERRAIN_TASK_ID,
    PhantomXCommandConfig,
    PhantomXCurriculumConfig,
    PhantomXTaskConfig,
    PhantomXTrainingConfig,
    load_phantomx_discrete_terrain_config,
    load_phantomx_terrain_config,
    load_phantomx_training_config,
    parse_phantomx_training_config,
)
from .curriculum import PhantomXCommandCurriculum
from .pursuit import PhantomXPursuitCommand
from .registration import (
    create_phantomx_discrete_terrain_registration,
    create_phantomx_discrete_terrain_runner_config,
    create_phantomx_discrete_terrain_worker_config,
    create_phantomx_pursuit_registration,
    create_phantomx_pursuit_task,
    create_phantomx_pursuit_worker_config,
    create_phantomx_registration,
    create_phantomx_runner_config,
    create_phantomx_task,
    create_phantomx_task_config,
    create_phantomx_terrain_registration,
    create_phantomx_terrain_runner_config,
    create_phantomx_terrain_worker_config,
    create_phantomx_worker_config,
    register_phantomx,
)
from .task import PhantomXTask

__all__ = [
    "PHANTOMX_COMMAND_FIELDS",
    "PHANTOMX_PURSUIT_ENVIRONMENT_ID",
    "PHANTOMX_PURSUIT_TASK_ID",
    "PHANTOMX_FEET",
    "PHANTOMX_DISCRETE_TERRAIN_TASK_ID",
    "PHANTOMX_DISCRETE_TERRAIN_ENVIRONMENT_ID",
    "PHANTOMX_ENVIRONMENT_ID",
    "PHANTOMX_ROBOT_ID",
    "PHANTOMX_SLOT_ISOLATED_ENVIRONMENT_ID",
    "PHANTOMX_TASK_ID",
    "PHANTOMX_TERRAIN_ENVIRONMENT_ID",
    "PHANTOMX_TERRAIN_TASK_ID",
    "PHANTOMX_TASK_VERSION",
    "PhantomXCommandConfig",
    "PhantomXCommandCurriculum",
    "PhantomXCurriculumConfig",
    "PhantomXTask",
    "PhantomXTaskConfig",
    "PhantomXTrainingConfig",
    "create_phantomx_registration",
    "create_phantomx_discrete_terrain_registration",
    "create_phantomx_discrete_terrain_runner_config",
    "create_phantomx_discrete_terrain_worker_config",
    "create_phantomx_terrain_registration",
    "create_phantomx_terrain_runner_config",
    "create_phantomx_terrain_worker_config",
    "create_phantomx_runner_config",
    "create_phantomx_task",
    "create_phantomx_task_config",
    "create_phantomx_worker_config",
    "create_phantomx_pursuit_registration",
    "create_phantomx_pursuit_task",
    "create_phantomx_pursuit_worker_config",
    "PhantomXPursuitCommand",
    "load_phantomx_terrain_config",
    "load_phantomx_discrete_terrain_config",
    "load_phantomx_training_config",
    "parse_phantomx_training_config",
    "register_phantomx",
]
