[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "uerl-example-direct-cartpole-direct"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = ["ue-rl-engine==1.0.0"]

[project.entry-points."uerl.tasks"]
example-direct-cartpole = "example_direct_cartpole:create_registration"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
example_direct_cartpole = ["reward.yaml"]
