"""Expose public types without loading the training runtime for host tools."""

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .core.config import (
        ActuatorConfig,
        ActuatorSpec,
        BoundResetTarget,
        ConstraintFrame,
        DirectTaskConfig,
        JointTopology,
        LaunchMode,
        LoggingConfig,
        ObservationConfig,
        ObservationSpec,
        ObsType,
        PresentationMode,
        ProtocolRequirements,
        ResetConfig,
        ResetTarget,
        ResetTargetType,
        ResolvedRunConfig,
        RobotConfig,
        RobotSpec,
        RobotTopology,
        RslRlRunnerConfig,
        RunConfigResolver,
        RunManifest,
        RunRecorder,
        SessionConfig,
        WorkerConfig,
        load_robot_config,
        merge_robot_spec,
        parse_robot_config,
    )
    from .core.direct import (
        ROBOT_ACTUATOR_TARGET_FIELD,
        ROBOT_CONTACT_OBSERVATION_FRAME,
        ROBOT_JOINT_OBSERVATION_FRAME,
        ROBOT_OBSERVATION_FRAME,
        ROBOT_OBSERVATION_SOURCE,
        CapabilityOperation,
        CapabilityStatus,
        CurriculumManager,
        CurriculumStep,
        CurriculumTerm,
        DirectSession,
        DirectTask,
        DirectTaskCfg,
        InitialState,
        ObservationShapeTable,
        PhysicalCommandBatch,
        PostResetState,
        SessionSchema,
        StateBatch,
        StepContext,
        TaskCapabilities,
        TaskCapability,
        TerminationResult,
        TerrainCurriculum,
        TransitionState,
        UERLDirectEnv,
        resolve_robot_actions,
        robot_actuator_action_schema,
        robot_observation_schema,
        validate_robot_shape_agreement,
    )
    from .errors import ConfigError, ProtocolError, RegistryError, SessionError, UERLError
    from .runtime.session import (
        ProcessHandle,
        SessionInitialization,
        SessionState,
        UERLSession,
        UERLSessionAdapter,
        WorkerOwnership,
        WorkerProcessController,
    )
    from .tasks.cartpole import CartPoleTaskConfig

_EXPORT_MODULES = {
    'ActuatorConfig': '.core.config',
    'ActuatorSpec': '.core.config',
    'BoundResetTarget': '.core.config',
    'ConstraintFrame': '.core.config',
    'DirectTaskConfig': '.core.config',
    'JointTopology': '.core.config',
    'LaunchMode': '.core.config',
    'LoggingConfig': '.core.config',
    'ObservationConfig': '.core.config',
    'ObservationSpec': '.core.config',
    'ObsType': '.core.config',
    'PresentationMode': '.core.config',
    'ProtocolRequirements': '.core.config',
    'ResetConfig': '.core.config',
    'ResetTarget': '.core.config',
    'ResetTargetType': '.core.config',
    'ResolvedRunConfig': '.core.config',
    'RobotConfig': '.core.config',
    'RobotSpec': '.core.config',
    'RobotTopology': '.core.config',
    'RslRlRunnerConfig': '.core.config',
    'RunConfigResolver': '.core.config',
    'RunManifest': '.core.config',
    'RunRecorder': '.core.config',
    'SessionConfig': '.core.config',
    'WorkerConfig': '.core.config',
    'load_robot_config': '.core.config',
    'merge_robot_spec': '.core.config',
    'parse_robot_config': '.core.config',
    'ROBOT_ACTUATOR_TARGET_FIELD': '.core.direct',
    'ROBOT_CONTACT_OBSERVATION_FRAME': '.core.direct',
    'ROBOT_JOINT_OBSERVATION_FRAME': '.core.direct',
    'ROBOT_OBSERVATION_FRAME': '.core.direct',
    'ROBOT_OBSERVATION_SOURCE': '.core.direct',
    'CapabilityOperation': '.core.direct',
    'CapabilityStatus': '.core.direct',
    'CurriculumManager': '.core.direct',
    'CurriculumStep': '.core.direct',
    'CurriculumTerm': '.core.direct',
    'DirectSession': '.core.direct',
    'DirectTask': '.core.direct',
    'DirectTaskCfg': '.core.direct',
    'InitialState': '.core.direct',
    'ObservationShapeTable': '.core.direct',
    'PhysicalCommandBatch': '.core.direct',
    'PostResetState': '.core.direct',
    'SessionSchema': '.core.direct',
    'StateBatch': '.core.direct',
    'StepContext': '.core.direct',
    'TaskCapabilities': '.core.direct',
    'TaskCapability': '.core.direct',
    'TerminationResult': '.core.direct',
    'TerrainCurriculum': '.core.direct',
    'TransitionState': '.core.direct',
    'UERLDirectEnv': '.core.direct',
    'resolve_robot_actions': '.core.direct',
    'robot_actuator_action_schema': '.core.direct',
    'robot_observation_schema': '.core.direct',
    'validate_robot_shape_agreement': '.core.direct',
    'ConfigError': '.errors',
    'ProtocolError': '.errors',
    'RegistryError': '.errors',
    'SessionError': '.errors',
    'UERLError': '.errors',
    'ProcessHandle': '.runtime.session',
    'SessionInitialization': '.runtime.session',
    'SessionState': '.runtime.session',
    'UERLSession': '.runtime.session',
    'UERLSessionAdapter': '.runtime.session',
    'WorkerOwnership': '.runtime.session',
    'WorkerProcessController': '.runtime.session',
    'CartPoleTaskConfig': '.tasks.cartpole',
}

__all__ = [
    "ActuatorConfig",
    "ActuatorSpec",
    "BoundResetTarget",
    "ConfigError",
    "ConstraintFrame",
    "DirectTaskCfg",
    "CartPoleTaskConfig",
    "DirectSession",
    "DirectTask",
    "CapabilityOperation",
    "CapabilityStatus",
    "CurriculumManager",
    "CurriculumStep",
    "CurriculumTerm",
    "UERLDirectEnv",
    "DirectTaskConfig",
    "TaskCapabilities",
    "TaskCapability",
    "LaunchMode",
    "ROBOT_ACTUATOR_TARGET_FIELD",
    "ObservationShapeTable",
    "ROBOT_CONTACT_OBSERVATION_FRAME",
    "ROBOT_JOINT_OBSERVATION_FRAME",
    "resolve_robot_actions",
    "robot_actuator_action_schema",
    "ROBOT_OBSERVATION_FRAME",
    "ROBOT_OBSERVATION_SOURCE",
    "robot_observation_schema",
    "validate_robot_shape_agreement",
    "LoggingConfig",
    "InitialState",
    "ObsType",
    "ObservationConfig",
    "ObservationSpec",
    "PresentationMode",
    "PhysicalCommandBatch",
    "PostResetState",
    "ProtocolError",
    "ProtocolRequirements",
    "RegistryError",
    "ResetConfig",
    "ResetTarget",
    "ResetTargetType",
    "ResolvedRunConfig",
    "RobotConfig",
    "RobotSpec",
    "RobotTopology",
    "JointTopology",
    "RunManifest",
    "RunRecorder",
    "RslRlRunnerConfig",
    "RunConfigResolver",
    "SessionConfig",
    "SessionError",
    "SessionInitialization",
    "SessionSchema",
    "SessionState",
    "StateBatch",
    "StepContext",
    "TerrainCurriculum",
    "TerminationResult",
    "TransitionState",
    "UERLError",
    "UERLSession",
    "WorkerConfig",
    "ProcessHandle",
    "WorkerOwnership",
    "WorkerProcessController",
    "UERLSessionAdapter",
    "load_robot_config",
    "merge_robot_spec",
    "parse_robot_config",
]


def __getattr__(name: str) -> Any:
    """Load a public type only when it is requested and cache its exact object."""
    module = _EXPORT_MODULES.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
